#!/usr/bin/env python3
"""Read version from pixi.toml and write bison/_version.mojo."""
import tomllib
import pathlib

root = pathlib.Path(__file__).parent.parent
version = tomllib.loads((root / "pixi.toml").read_text())["project"]["version"]
out = (
    "# AUTO-GENERATED by scripts/gen_version.py — do not edit.\n"
    f'alias VERSION: String = "{version}"\n'
)
(root / "bison" / "_version.mojo").write_text(out)
print(f"bison/_version.mojo: version = {version}")
