#!/usr/bin/env python3
"""Read version from pixi.toml and write bison/_version.mojo."""
import tomllib
import pathlib

root = pathlib.Path(__file__).parent.parent
version = tomllib.loads((root / "pixi.toml").read_text())["workspace"]["version"]
out = (
    "# AUTO-GENERATED by scripts/gen_version.py — do not edit.\n"
    f'comptime VERSION: String = "{version}"\n'
)
dest = root / "bison" / "_version.mojo"
if not dest.exists() or dest.read_text() != out:
    dest.write_text(out)
    print(f"bison/_version.mojo: version = {version}")
else:
    print(f"bison/_version.mojo: up to date ({version})")
